import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Document, Letterhead } from '../types';
import { formatCurrency, numberToWords } from './calculations';
import { DOCUMENT_LABELS } from './documentLabels';
import { format } from 'date-fns';

const PAGE_WIDTH = 210; // A4 mm
const PAGE_HEIGHT = 297;
const MARGIN = 10;
const HEADER_HEIGHT = 40;
const FOOTER_HEIGHT = 20;
const CONTENT_TOP = MARGIN + HEADER_HEIGHT + 5;
const CONTENT_BOTTOM = PAGE_HEIGHT - MARGIN - FOOTER_HEIGHT - 5;

async function loadImage(src: string): Promise<string | null> {
  if (!src) return null;
  return src; // base64 already
}

function drawHeader(doc: jsPDF, letterhead: Letterhead, pageWidth: number) {
  const y = MARGIN;
  if (letterhead.headerImage) {
    try {
      // Use full width from edge to edge for header
      doc.addImage(letterhead.headerImage, 'JPEG', 0, 0, pageWidth, HEADER_HEIGHT);
    } catch (error) {
      console.error('Error loading header image:', error);
      drawFallbackHeader(doc, letterhead, y, pageWidth);
    }
  } else {
    drawFallbackHeader(doc, letterhead, y, pageWidth);
  }
}

function drawFallbackHeader(doc: jsPDF, letterhead: Letterhead, y: number, pageWidth: number) {
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageWidth, HEADER_HEIGHT, 'F');

  if (letterhead.logo) {
    try {
      doc.addImage(letterhead.logo, 'PNG', MARGIN + 2, y + 5, 30, 30);
    } catch (e) { 
      console.error('Error loading logo:', e);
    }
  }

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(letterhead.companyName || 'B2P International', pageWidth / 2, y + 18, { align: 'center' });

  if (letterhead.tagline) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(letterhead.tagline, pageWidth / 2, y + 26, { align: 'center' });
  }
  doc.setTextColor(0, 0, 0);
}

function drawFooter(doc: jsPDF, letterhead: Letterhead, pageWidth: number, pageNum: number, totalPages: number) {
  const y = PAGE_HEIGHT - FOOTER_HEIGHT;
  if (letterhead.footerImage) {
    try {
      // Use full width from edge to edge for footer
      doc.addImage(letterhead.footerImage, 'JPEG', 0, y, pageWidth, FOOTER_HEIGHT);
    } catch (error) {
      console.error('Error loading footer image:', error);
      drawFallbackFooter(doc, letterhead, y, pageWidth, pageNum, totalPages);
    }
  } else {
    drawFallbackFooter(doc, letterhead, y, pageWidth, pageNum, totalPages);
  }
}

function drawFallbackFooter(doc: jsPDF, _letterhead: Letterhead, y: number, pageWidth: number, pageNum: number, totalPages: number) {
  doc.setDrawColor(220, 220, 220);
  doc.line(MARGIN, y + 2, pageWidth - MARGIN, y + 2);
  doc.setFontSize(7);
  doc.setTextColor(120, 120, 120);
  doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth / 2, y + 8, { align: 'center' });
  doc.text('Generated by B2P International Document Management System', pageWidth / 2, y + 13, { align: 'center' });
  doc.setTextColor(0, 0, 0);
}

export async function generatePDF(document: Document, letterhead: Letterhead): Promise<jsPDF> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = PAGE_WIDTH;

  // We need 2 passes: first to know total pages, second to render
  // For simplicity, we render once and add headers/footers after
  let currentY = CONTENT_TOP;

  // --- Page 1 header ---
  drawHeader(doc, letterhead, pageWidth);

  // Document title & number
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(MARGIN, currentY, pageWidth - MARGIN * 2, 16, 3, 3, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(30, 64, 175);
  doc.text(DOCUMENT_LABELS[document.type].toUpperCase(), MARGIN + 6, currentY + 7);
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`# ${document.number}`, pageWidth - MARGIN - 6, currentY + 7, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Date: ${format(new Date(document.date), 'dd MMM yyyy')}`, pageWidth - MARGIN - 6, currentY + 13, { align: 'right' });
  doc.setTextColor(0, 0, 0);
  currentY += 22;

  // Bill To section
  doc.setFillColor(239, 246, 255);
  doc.rect(MARGIN, currentY, (pageWidth - MARGIN * 2) / 2 - 3, 30, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(37, 99, 235);
  doc.text('BILL TO', MARGIN + 4, currentY + 6);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(0, 0, 0);
  doc.text(document.customerName || 'N/A', MARGIN + 4, currentY + 13);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  if (document.customerCompany) doc.text(document.customerCompany, MARGIN + 4, currentY + 19);
  if (document.customerAddress) {
    const lines = doc.splitTextToSize(document.customerAddress, (pageWidth - MARGIN * 2) / 2 - 10);
    doc.text(lines[0] || '', MARGIN + 4, currentY + 25);
  }

  // Info section right
  const infoX = MARGIN + (pageWidth - MARGIN * 2) / 2 + 3;
  const infoW = (pageWidth - MARGIN * 2) / 2 - 3;
  doc.setFillColor(248, 250, 252);
  doc.rect(infoX, currentY, infoW, 30, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(37, 99, 235);
  doc.text('DOCUMENT INFO', infoX + 4, currentY + 6);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(8);
  if (document.dueDate) {
    doc.text(`Due Date: ${format(new Date(document.dueDate), 'dd MMM yyyy')}`, infoX + 4, currentY + 13);
  }
  if (document.customerGST) doc.text(`GST: ${document.customerGST}`, infoX + 4, currentY + 19);
  if (document.customerEmail) doc.text(`Email: ${document.customerEmail}`, infoX + 4, currentY + 25);

  currentY += 36;

  // Items table
  const tableColumns = ['#', 'Description', 'Qty', 'Unit', 'Rate (₹)', 'Disc%', 'Tax%', 'Amount (₹)'];
  const tableRows = document.items.map((item, i) => [
    String(i + 1),
    item.description,
    String(item.quantity),
    item.unit,
    formatCurrency(item.rate).replace('₹', '').trim(),
    `${item.discount}%`,
    `${item.taxRate}%`,
    formatCurrency(item.subtotal).replace('₹', '').trim(),
  ]);

  let finalY = currentY;

  autoTable(doc, {
    head: [tableColumns],
    body: tableRows,
    startY: currentY,
    margin: { left: MARGIN, right: MARGIN, top: CONTENT_TOP, bottom: PAGE_HEIGHT - CONTENT_BOTTOM },
    headStyles: {
      fillColor: [37, 99, 235],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
    },
    bodyStyles: { fontSize: 8 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      0: { cellWidth: 8 },
      1: { cellWidth: 55 },
      2: { cellWidth: 12 },
      3: { cellWidth: 15 },
      4: { cellWidth: 22 },
      5: { cellWidth: 12 },
      6: { cellWidth: 12 },
      7: { cellWidth: 22 },
    },
    didDrawPage: (data) => {
      if (data.pageNumber > 1) {
        drawHeader(doc, letterhead, pageWidth);
      }
      drawFooter(doc, letterhead, pageWidth, data.pageNumber, data.pageCount);
    },
  });

  finalY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 5;

  // Totals
  const totalsX = pageWidth - MARGIN - 70;
  const totalsW = 70;

  const addTotalRow = (label: string, value: string, bold = false, color?: [number, number, number]) => {
    if (finalY > CONTENT_BOTTOM - 10) {
      doc.addPage();
      drawHeader(doc, letterhead, pageWidth);
      finalY = CONTENT_TOP;
    }
    if (bold) {
      doc.setFont('helvetica', 'bold');
      doc.setFillColor(37, 99, 235);
      doc.rect(totalsX, finalY - 4, totalsW, 8, 'F');
      doc.setTextColor(255, 255, 255);
    } else {
      doc.setFont('helvetica', 'normal');
      doc.setFillColor(248, 250, 252);
      doc.rect(totalsX, finalY - 4, totalsW, 7, 'F');
      doc.setTextColor(color ? color[0] : 0, color ? color[1] : 0, color ? color[2] : 0);
    }
    doc.setFontSize(9);
    doc.text(label, totalsX + 3, finalY + 0);
    doc.text(value, totalsX + totalsW - 3, finalY + 0, { align: 'right' });
    doc.setTextColor(0, 0, 0);
    finalY += bold ? 9 : 8;
  };

  addTotalRow('Subtotal:', formatCurrency(document.subtotal));
  if (document.totalDiscount > 0) addTotalRow('Discount:', `- ${formatCurrency(document.totalDiscount)}`, false, [220, 38, 38]);
  if (document.totalTax > 0) addTotalRow('Tax/GST:', `+ ${formatCurrency(document.totalTax)}`);
  addTotalRow('GRAND TOTAL:', formatCurrency(document.grandTotal), true);

  finalY += 5;

  // Amount in words
  if (finalY < CONTENT_BOTTOM - 15) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(80, 80, 80);
    const words = numberToWords(document.grandTotal);
    doc.text(`Amount in words: ${words}`, MARGIN, finalY);
    finalY += 10;
  }

  // Notes and Terms
  if (document.notes && finalY < CONTENT_BOTTOM - 20) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(0, 0, 0);
    doc.text('Notes:', MARGIN, finalY);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(80, 80, 80);
    const noteLines = doc.splitTextToSize(document.notes, (pageWidth - MARGIN * 2) * 0.6);
    doc.text(noteLines, MARGIN, finalY + 5);
    finalY += 5 + noteLines.length * 4 + 5;
  }

  if (document.terms && finalY < CONTENT_BOTTOM - 20) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(0, 0, 0);
    doc.text('Terms & Conditions:', MARGIN, finalY);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(80, 80, 80);
    const termLines = doc.splitTextToSize(document.terms, (pageWidth - MARGIN * 2) * 0.75);
    doc.text(termLines, MARGIN, finalY + 5);
    finalY += 5 + termLines.length * 4 + 5;
  }

  // Signature & Seal
  if (finalY < CONTENT_BOTTOM - 40) {
    const sigY = Math.max(finalY + 10, CONTENT_BOTTOM - 40);
    
    // Company seal on the left
    if (letterhead.seal) {
      try { 
        doc.addImage(letterhead.seal, 'PNG', MARGIN + 5, sigY, 30, 30); 
      } catch (e) { 
        console.error('Error loading seal:', e);
      }
    }
    
    // Authorized signature on the right
    if (letterhead.signature) {
      try { 
        doc.addImage(letterhead.signature, 'PNG', pageWidth - MARGIN - 50, sigY + 5, 45, 15); 
      } catch (e) { 
        console.error('Error loading signature:', e);
      }
    }
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.line(pageWidth - MARGIN - 50, sigY + 25, pageWidth - MARGIN - 5, sigY + 25);
    doc.text('Authorized Signature', pageWidth - MARGIN - 27.5, sigY + 30, { align: 'center' });
  }

  // Draw footer on page 1 (if only 1 page, autoTable didn't call didDrawPage for page 1)
  const totalPagesNum = doc.getNumberOfPages();
  for (let p = 1; p <= totalPagesNum; p++) {
    doc.setPage(p);
    drawFooter(doc, letterhead, pageWidth, p, totalPagesNum);
  }

  return doc;
}

export async function downloadPDF(document: Document, letterhead: Letterhead): Promise<void> {
  const doc = await generatePDF(document, letterhead);
  doc.save(`${document.number}_${document.customerName.replace(/\s+/g, '_')}.pdf`);
}
